language: ruby
sudo: false
cache: bundler
script: ./script/ci
rvm:
  - 2.3.5
  - 2.4.2
  - ruby-head
  - jruby-9.1.13.0
  - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
